<?php

namespace App\Modules\Finance\Database\Seeders;

use App\Modules\Finance\CostCollector\Models\ExpenseCode;

/**
 * NE-001…NE-023 — cash movements that are NOT expenses, plus inventory,
 * prepayments, tax settlements and capital items.
 *
 * The block the brief is most emphatic about: these are the transactions that,
 * miscoded, turn a cash-spend report into a fictional P&L. A float top-up is not
 * a cost. Neither is an advance until it is retired with receipts, nor material
 * until it is issued to a job.
 *
 * Held separately from ExpenseCodeSeeder only because each row carries distinct
 * evidence, controls and Job ID rules, unlike the direct-materials family which
 * shares one set.
 */
final class NonExpenseCodes
{
    private const DEFAULTS = [
        'accounting_class' => 'Balance sheet / Not an expense',
        'expense_family' => 'Non-expense cash movement',
        'recording_rule' => 'Post to the named balance-sheet account. Do not put it in the P&L as an expense.',
        'default_cost_centre' => 'Finance',
        'project_activity' => 'Not applicable',
        'inventory_treatment' => 'Balance-sheet item',
        'vat_default' => 'Depends on the later invoice',
        'wht_review' => 'No, unless the later supplier invoice is liable',
        'pl_report_line' => 'No immediate P&L',
        'cash_flow_class' => 'operating',
        'cash_flow_note' => 'Operating unless noted',
        'job_id_rule' => ExpenseCode::JOB_NOT_ALLOWED,
        'job_id_rule_note' => 'Not allowed',
        'minimum_evidence' => [
            ['key' => 'voucher', 'label' => 'Approved voucher', 'required' => true],
            ['key' => 'payment_proof', 'label' => 'Payment proof', 'required' => true],
        ],
        'extra_operational_data' => [
            ['key' => 'counterparty', 'label' => 'Counterparty', 'type' => 'text', 'required' => true],
            ['key' => 'settlement_reference', 'label' => 'Settlement reference', 'type' => 'text', 'required' => true],
            ['key' => 'due_date', 'label' => 'Due / retirement date', 'type' => 'date', 'required' => false],
        ],
    ];

    /** @return iterable<array<string, mixed>> */
    public static function rows(): iterable
    {
        foreach (self::definitions() as $row) {
            yield array_merge(self::DEFAULTS, $row);
        }
    }

    /** @return array<int, array<string, mixed>> */
    private static function definitions(): array
    {
        return [
            [
                'code' => 'NE-001', 'expense_type' => 'Petty-cash float top-up',
                'simple_meaning' => 'Money moved from bank or M-Pesa into an approved petty-cash float.',
                'example' => 'KES 50,000 moved from NCBA bank to the workshop petty-cash custodian.',
                'default_debit_gl' => '1030 Petty Cash Float',
                'key_control' => 'Top-up must match an approved float limit; it is not an expense.',
            ],
            [
                'code' => 'NE-002', 'expense_type' => 'Transfer between company accounts',
                'simple_meaning' => 'Money moved between two WNG-owned bank, M-Pesa or cash accounts.',
                'example' => 'KES 100,000 moved from bank to company M-Pesa.',
                'default_debit_gl' => 'Receiving cash/bank account',
                'key_control' => 'Both sides of the transfer must use the same transfer reference.',
            ],
            [
                'code' => 'NE-003', 'expense_type' => 'Staff advance / imprest issued',
                'simple_meaning' => 'Cash given to a staff member before the staff member spends it.',
                'example' => 'Mutuku receives KES 15,000 to buy site materials.',
                'default_debit_gl' => '1300 Staff Advances',
                'job_id_rule' => ExpenseCode::JOB_OPTIONAL, 'job_id_rule_note' => 'Optional',
                'key_control' => 'The advance stays open until receipts and unused cash are returned.',
                'extra_operational_data' => [
                    ['key' => 'employee_id', 'label' => 'Employee', 'type' => 'text', 'required' => true],
                    ['key' => 'purpose', 'label' => 'Purpose', 'type' => 'textarea', 'required' => true],
                    ['key' => 'retirement_deadline', 'label' => 'Retirement deadline', 'type' => 'date', 'required' => true],
                ],
            ],
            [
                'code' => 'NE-004', 'expense_type' => 'Staff advance retired with receipts',
                'simple_meaning' => 'Valid receipts are used to clear an earlier staff advance.',
                'example' => 'Mutuku submits receipts for timber, transport and meals.',
                'default_debit_gl' => 'Relevant expense, WIP, inventory or asset account',
                'job_id_rule' => ExpenseCode::JOB_CONDITIONAL, 'job_id_rule_note' => 'Required when project-related',
                'key_control' => 'Each receipt must be recorded as a separate allocation line.',
            ],
            [
                'code' => 'NE-005', 'expense_type' => 'Unused advance returned',
                'simple_meaning' => 'Unspent money from an advance is returned to the company.',
                'example' => 'KES 1,800 is returned after a site purchase.',
                'default_debit_gl' => '1030 Petty Cash Float or bank',
                'job_id_rule' => ExpenseCode::JOB_CONDITIONAL, 'job_id_rule_note' => 'Use the original Job ID',
                'key_control' => "Return must reduce the employee's open advance.",
            ],
            [
                'code' => 'NE-006', 'expense_type' => 'Supplier deposit / advance',
                'simple_meaning' => 'Money paid to a supplier before goods or services are received.',
                'example' => '50% deposit paid for outsourced LED screens.',
                'default_debit_gl' => '1310 Supplier Advances',
                'job_id_rule' => ExpenseCode::JOB_OPTIONAL, 'job_id_rule_note' => 'Optional',
                'requires_supplier' => true,
                'key_control' => 'Move to expense, WIP, inventory or asset only after receipt/acceptance.',
                'extra_operational_data' => [
                    ['key' => 'supplier_id', 'label' => 'Supplier', 'type' => 'text', 'required' => true],
                    ['key' => 'purchase_order', 'label' => 'PO number', 'type' => 'text', 'required' => true],
                    ['key' => 'expected_delivery', 'label' => 'Expected delivery date', 'type' => 'date', 'required' => true],
                ],
            ],
            [
                'code' => 'NE-007', 'expense_type' => 'Refundable deposit paid',
                'simple_meaning' => 'Money WNG expects to recover after meeting agreed conditions.',
                'example' => 'Venue access deposit or equipment-hire security deposit.',
                'default_debit_gl' => '1320 Refundable Deposits',
                'job_id_rule' => ExpenseCode::JOB_OPTIONAL, 'job_id_rule_note' => 'Optional',
                'key_control' => 'Review overdue deposits monthly.',
                'extra_operational_data' => [
                    ['key' => 'refund_terms', 'label' => 'Refund terms', 'type' => 'textarea', 'required' => true],
                    ['key' => 'return_date', 'label' => 'Expected return date', 'type' => 'date', 'required' => true],
                    ['key' => 'responsible_person', 'label' => 'Responsible person', 'type' => 'text', 'required' => true],
                ],
            ],
            [
                'code' => 'NE-008', 'expense_type' => 'Material bought for store',
                'accounting_class' => 'Inventory asset', 'expense_family' => 'Inventory purchase',
                'simple_meaning' => 'Material purchased for future use and not yet assigned to a job.',
                'example' => 'Ten MDF boards purchased and received into the workshop store.',
                'default_debit_gl' => '1200 Raw-material Inventory',
                'job_id_rule' => ExpenseCode::JOB_CONDITIONAL,
                'job_id_rule_note' => 'Not required at purchase; required at issue',
                'default_cost_centre' => 'Stores', 'project_activity' => 'Procurement / Receiving',
                'inventory_treatment' => 'Inventory until issued',
                'vat_default' => 'Recoverable if eligible and supported',
                'default_vat_treatment_code' => 'STD16-REC',
                'cash_flow_note' => 'Operating', 'requires_supplier' => true,
                'key_control' => 'Do not expense at purchase; expense or WIP starts when material is issued.',
                'minimum_evidence' => [
                    ['key' => 'purchase_order', 'label' => 'Purchase order', 'required' => true],
                    ['key' => 'etims_invoice', 'label' => 'Supplier invoice / eTIMS', 'required' => true],
                    ['key' => 'grn', 'label' => 'Delivery note and GRN', 'required' => true],
                ],
                'extra_operational_data' => [
                    ['key' => 'item_code', 'label' => 'Item code', 'type' => 'text', 'required' => true],
                    ['key' => 'quantity', 'label' => 'Quantity', 'type' => 'number', 'required' => true],
                    ['key' => 'uom', 'label' => 'Unit of measure', 'type' => 'text', 'required' => true],
                    ['key' => 'unit_price', 'label' => 'Unit price', 'type' => 'number', 'required' => true],
                    ['key' => 'batch', 'label' => 'Batch', 'type' => 'text', 'required' => false],
                    ['key' => 'store_location', 'label' => 'Store location', 'type' => 'text', 'required' => true],
                ],
            ],
            [
                'code' => 'NE-009', 'expense_type' => 'Material issued from store to project',
                'accounting_class' => 'Internal stock movement', 'expense_family' => 'Inventory issue',
                'simple_meaning' => 'Inventory is taken from stores and used on a named job.',
                'example' => 'Three plywood boards issued to the Visa activation job.',
                'default_debit_gl' => '1211 Project WIP – Direct Materials',
                'job_id_rule' => ExpenseCode::JOB_REQUIRED, 'job_id_rule_note' => 'Required',
                'default_cost_centre' => 'Stores / Production', 'project_activity' => 'Production',
                'inventory_treatment' => 'Reduce inventory and increase project WIP',
                'vat_default' => 'No VAT on internal issue', 'default_vat_treatment_code' => 'OOS',
                'cash_flow_class' => 'none', 'cash_flow_note' => 'No cash flow',
                'key_control' => 'Credit inventory at the approved inventory costing method.',
                'minimum_evidence' => [
                    ['key' => 'material_requisition', 'label' => 'Approved material requisition', 'required' => true],
                    ['key' => 'issue_note', 'label' => 'Stores issue note', 'required' => true],
                ],
                'extra_operational_data' => [
                    ['key' => 'item_code', 'label' => 'Item', 'type' => 'text', 'required' => true],
                    ['key' => 'quantity', 'label' => 'Quantity', 'type' => 'number', 'required' => true],
                    ['key' => 'uom', 'label' => 'Unit of measure', 'type' => 'text', 'required' => true],
                    ['key' => 'unit_price', 'label' => 'Weighted / standard cost', 'type' => 'number', 'required' => true],
                    ['key' => 'receiver', 'label' => 'Received by', 'type' => 'text', 'required' => true],
                ],
            ],
            [
                'code' => 'NE-010', 'expense_type' => 'Material returned from project to store',
                'accounting_class' => 'Internal stock movement', 'expense_family' => 'Inventory return',
                'simple_meaning' => 'Unused project material is returned to inventory.',
                'example' => 'One unused acrylic sheet returned after production.',
                'default_debit_gl' => '1200 Raw-material Inventory',
                'job_id_rule' => ExpenseCode::JOB_REQUIRED, 'job_id_rule_note' => 'Required',
                'default_cost_centre' => 'Stores', 'project_activity' => 'Production return',
                'inventory_treatment' => 'Increase inventory and reduce WIP',
                'vat_default' => 'No VAT on internal return', 'default_vat_treatment_code' => 'OOS',
                'cash_flow_class' => 'none', 'cash_flow_note' => 'No cash flow',
                'key_control' => 'Use the same cost rate as the original issue.',
                'minimum_evidence' => [
                    ['key' => 'return_note', 'label' => 'Return note', 'required' => true],
                    ['key' => 'store_acceptance', 'label' => 'Store acceptance', 'required' => true],
                ],
                'extra_operational_data' => [
                    ['key' => 'item_code', 'label' => 'Item', 'type' => 'text', 'required' => true],
                    ['key' => 'quantity', 'label' => 'Quantity', 'type' => 'number', 'required' => true],
                    ['key' => 'condition', 'label' => 'Condition', 'type' => 'text', 'required' => true],
                    ['key' => 'original_issue_ref', 'label' => 'Original issue reference', 'type' => 'text', 'required' => true],
                ],
            ],
            [
                'code' => 'NE-011', 'expense_type' => 'Prepaid rent',
                'accounting_class' => 'Prepayment asset', 'expense_family' => 'Prepayments',
                'simple_meaning' => 'Rent paid now that relates to future months.',
                'example' => "Three months' workshop rent paid in advance.",
                'default_debit_gl' => '1340 Prepaid Expenses',
                'default_cost_centre' => 'Finance / Facilities', 'project_activity' => 'Administration',
                'inventory_treatment' => 'Release to expense monthly',
                'vat_default' => 'According to valid invoice',
                'key_control' => 'ERP must create an amortisation schedule.',
                'minimum_evidence' => [
                    ['key' => 'lease', 'label' => 'Lease agreement', 'required' => true],
                    ['key' => 'etims_invoice', 'label' => 'Invoice', 'required' => true],
                    ['key' => 'payment_proof', 'label' => 'Payment proof', 'required' => true],
                ],
                'extra_operational_data' => [
                    ['key' => 'service_start', 'label' => 'Service start date', 'type' => 'date', 'required' => true],
                    ['key' => 'service_end', 'label' => 'Service end date', 'type' => 'date', 'required' => true],
                    ['key' => 'monthly_release', 'label' => 'Monthly release amount', 'type' => 'number', 'required' => true],
                ],
            ],
            [
                'code' => 'NE-012', 'expense_type' => 'Prepaid insurance',
                'accounting_class' => 'Prepayment asset', 'expense_family' => 'Prepayments',
                'simple_meaning' => 'Insurance paid now that covers future months.',
                'example' => 'Annual vehicle and workshop insurance premium paid in July.',
                'default_debit_gl' => '1340 Prepaid Expenses',
                'project_activity' => 'Administration',
                'inventory_treatment' => 'Release to expense over the cover period',
                'vat_default' => 'Usually out of scope; use accountant-approved code',
                'default_vat_treatment_code' => 'OOS',
                'key_control' => 'No full expense on payment if the cover spans future periods.',
                'minimum_evidence' => [
                    ['key' => 'policy_schedule', 'label' => 'Policy schedule', 'required' => true],
                    ['key' => 'etims_invoice', 'label' => 'Invoice', 'required' => true],
                    ['key' => 'payment_proof', 'label' => 'Payment proof', 'required' => true],
                ],
                'extra_operational_data' => [
                    ['key' => 'policy_number', 'label' => 'Policy number', 'type' => 'text', 'required' => true],
                    ['key' => 'asset_or_vehicle', 'label' => 'Asset / vehicle', 'type' => 'text', 'required' => false],
                    ['key' => 'cover_start', 'label' => 'Cover start', 'type' => 'date', 'required' => true],
                    ['key' => 'cover_end', 'label' => 'Cover end', 'type' => 'date', 'required' => true],
                ],
            ],
            [
                'code' => 'NE-013', 'expense_type' => 'Input VAT recoverable',
                'accounting_class' => 'Tax asset', 'expense_family' => 'Input VAT',
                'simple_meaning' => 'VAT WNG can claim from KRA on an eligible business purchase.',
                'example' => 'KES 1,600 VAT on an eligible KES 10,000 material invoice.',
                'default_debit_gl' => '1330 Input VAT Recoverable',
                'job_id_rule' => ExpenseCode::JOB_CONDITIONAL, 'job_id_rule_note' => 'Follow the purchase',
                'project_activity' => 'Tax', 'inventory_treatment' => 'Tax receivable, not project cost',
                'vat_default' => 'Recoverable VAT', 'default_vat_treatment_code' => 'STD16-REC',
                'key_control' => 'Do not include recoverable VAT in project expense.',
                'minimum_evidence' => [
                    ['key' => 'etims_invoice', 'label' => 'Valid transmitted eTIMS invoice with buyer PIN', 'required' => true],
                ],
                'extra_operational_data' => [
                    ['key' => 'invoice_date', 'label' => 'Invoice date', 'type' => 'date', 'required' => true],
                    ['key' => 'cuin', 'label' => 'CUIN', 'type' => 'text', 'required' => true],
                    ['key' => 'supplier_pin', 'label' => 'Supplier KRA PIN', 'type' => 'text', 'required' => true],
                    ['key' => 'vat_rate', 'label' => 'VAT rate', 'type' => 'number', 'required' => true],
                    ['key' => 'claim_period', 'label' => 'Claim period', 'type' => 'text', 'required' => true],
                ],
            ],
            [
                'code' => 'NE-014', 'expense_type' => 'Withholding tax remitted',
                'accounting_class' => 'Liability settlement', 'expense_family' => 'Withholding Tax',
                'simple_meaning' => 'Tax earlier withheld from a supplier is paid to KRA.',
                'example' => 'KES 3,000 contractual WHT remitted to KRA.',
                'default_debit_gl' => '2120 Withholding Tax Payable',
                'job_id_rule' => ExpenseCode::JOB_CONDITIONAL, 'job_id_rule_note' => 'Use supplier/project reference',
                'project_activity' => 'Tax', 'inventory_treatment' => 'Reduce tax liability',
                'vat_default' => 'No VAT', 'default_vat_treatment_code' => 'OOS',
                'wht_review' => 'This is the settlement of WHT already deducted',
                'key_control' => 'Remittance must clear the supplier-level WHT liability.',
                'minimum_evidence' => [
                    ['key' => 'kra_slip', 'label' => 'KRA payment slip', 'required' => true],
                    ['key' => 'wht_certificate', 'label' => 'WHT certificate', 'required' => true],
                    ['key' => 'payment_proof', 'label' => 'Bank proof', 'required' => true],
                ],
                'extra_operational_data' => [
                    ['key' => 'supplier_pin', 'label' => 'Supplier KRA PIN', 'type' => 'text', 'required' => true],
                    ['key' => 'payment_month', 'label' => 'Payment month', 'type' => 'text', 'required' => true],
                    ['key' => 'wht_type', 'label' => 'WHT type', 'type' => 'text', 'required' => true],
                    ['key' => 'certificate_number', 'label' => 'Certificate number', 'type' => 'text', 'required' => true],
                ],
            ],
            [
                'code' => 'NE-015', 'expense_type' => 'VAT or corporation tax paid',
                'accounting_class' => 'Liability / tax settlement', 'expense_family' => 'Tax payment',
                'simple_meaning' => 'Payment of tax owed to KRA; it is normally settlement of a tax liability.',
                'example' => 'Monthly VAT balance or annual corporation tax instalment paid.',
                'default_debit_gl' => 'Relevant tax payable or income-tax receivable',
                'project_activity' => 'Tax', 'inventory_treatment' => 'Balance-sheet settlement',
                'vat_default' => 'No VAT', 'default_vat_treatment_code' => 'OOS', 'wht_review' => 'No',
                'key_control' => 'Never classify VAT remittance as an operating expense.',
                'minimum_evidence' => [
                    ['key' => 'tax_return', 'label' => 'Tax return', 'required' => true],
                    ['key' => 'payment_registration', 'label' => 'Payment registration', 'required' => true],
                    ['key' => 'payment_proof', 'label' => 'Bank proof', 'required' => true],
                ],
                'extra_operational_data' => [
                    ['key' => 'tax_obligation', 'label' => 'Tax obligation', 'type' => 'text', 'required' => true],
                    ['key' => 'tax_period', 'label' => 'Tax period', 'type' => 'text', 'required' => true],
                    ['key' => 'kra_reference', 'label' => 'KRA reference', 'type' => 'text', 'required' => true],
                ],
            ],
            [
                'code' => 'NE-016', 'expense_type' => 'Loan principal repayment',
                'accounting_class' => 'Liability settlement', 'expense_family' => 'Borrowings',
                'simple_meaning' => 'The part of a loan payment that reduces the amount borrowed.',
                'example' => 'KES 200,000 principal paid on an equipment loan.',
                'default_debit_gl' => '2300 Loans Payable',
                'project_activity' => 'Financing', 'inventory_treatment' => 'Reduce loan liability',
                'vat_default' => 'No VAT', 'default_vat_treatment_code' => 'OOS',
                'cash_flow_class' => 'financing', 'cash_flow_note' => 'Financing',
                'key_control' => 'Only the interest and bank fees may go to P&L.',
                'minimum_evidence' => [
                    ['key' => 'loan_statement', 'label' => 'Loan statement', 'required' => true],
                    ['key' => 'payment_proof', 'label' => 'Payment proof', 'required' => true],
                ],
                'extra_operational_data' => [
                    ['key' => 'loan_account', 'label' => 'Loan account', 'type' => 'text', 'required' => true],
                    ['key' => 'principal', 'label' => 'Principal', 'type' => 'number', 'required' => true],
                    ['key' => 'interest', 'label' => 'Interest', 'type' => 'number', 'required' => true],
                    ['key' => 'fees', 'label' => 'Fees', 'type' => 'number', 'required' => false],
                ],
            ],
            [
                'code' => 'NE-017', 'expense_type' => 'Owner drawings / dividend',
                'accounting_class' => 'Equity movement', 'expense_family' => 'Owner distribution',
                'simple_meaning' => 'Money paid to an owner because of ownership, not for business goods or services.',
                'example' => 'Dividend paid to shareholders after approval.',
                'default_debit_gl' => 'Equity / Dividends Payable',
                'project_activity' => 'Financing', 'inventory_treatment' => 'Equity or liability movement',
                'vat_default' => 'No VAT', 'default_vat_treatment_code' => 'OOS',
                'cash_flow_class' => 'financing', 'cash_flow_note' => 'Financing',
                'key_control' => 'Do not post as a business expense.',
                'minimum_evidence' => [
                    ['key' => 'board_approval', 'label' => 'Board / shareholder approval', 'required' => true],
                    ['key' => 'payment_proof', 'label' => 'Payment proof', 'required' => true],
                ],
                'extra_operational_data' => [
                    ['key' => 'resolution_reference', 'label' => 'Resolution reference', 'type' => 'text', 'required' => true],
                    ['key' => 'beneficiary', 'label' => 'Beneficiary', 'type' => 'text', 'required' => true],
                    ['key' => 'tax_treatment', 'label' => 'Tax treatment', 'type' => 'text', 'required' => true],
                ],
            ],
            [
                'code' => 'NE-018', 'expense_type' => 'Customer advance / deposit received',
                'accounting_class' => 'Customer liability', 'expense_family' => 'Client deposits',
                'simple_meaning' => 'Money received from a client before WNG earns the revenue.',
                'example' => '70% deposit received before booth production starts.',
                'default_debit_gl' => 'Bank / Cash (credit is 2200 Client Deposits)',
                'job_id_rule' => ExpenseCode::JOB_REQUIRED, 'job_id_rule_note' => 'Required',
                'default_cost_centre' => 'Finance / Sales', 'project_activity' => 'Client billing',
                'inventory_treatment' => 'Liability until revenue recognition',
                'vat_default' => 'Output VAT timing according to tax invoice policy',
                'key_control' => 'Do not treat the deposit itself as profit.',
                'minimum_evidence' => [
                    ['key' => 'client_contract', 'label' => 'Client contract / PO', 'required' => true],
                    ['key' => 'invoice', 'label' => 'Invoice', 'required' => true],
                    ['key' => 'bank_receipt', 'label' => 'Bank receipt', 'required' => true],
                ],
                'extra_operational_data' => [
                    ['key' => 'client', 'label' => 'Client', 'type' => 'text', 'required' => true],
                    ['key' => 'invoice_number', 'label' => 'Invoice number', 'type' => 'text', 'required' => true],
                    ['key' => 'revenue_recognition_status', 'label' => 'Revenue recognition status', 'type' => 'text', 'required' => true],
                ],
            ],
            [
                'code' => 'NE-019', 'expense_type' => 'Client refund / credit note',
                'accounting_class' => 'Revenue reversal or liability settlement', 'expense_family' => 'Client refunds',
                'simple_meaning' => 'Money returned because WNG owes the client or is reversing revenue.',
                'example' => 'Refund of an unused client deposit after cancellation.',
                'default_debit_gl' => '2200 Client Deposits or relevant revenue/returns account',
                'job_id_rule' => ExpenseCode::JOB_REQUIRED, 'job_id_rule_note' => 'Required',
                'default_cost_centre' => 'Finance / Sales', 'project_activity' => 'Client billing',
                'inventory_treatment' => 'Reduce liability or revenue',
                'vat_default' => 'Tax credit note where required',
                'key_control' => 'Do not hide refunds inside miscellaneous expenses.',
                'minimum_evidence' => [
                    ['key' => 'credit_note', 'label' => 'Approved credit note', 'required' => true],
                    ['key' => 'client_confirmation', 'label' => 'Client confirmation', 'required' => true],
                    ['key' => 'payment_proof', 'label' => 'Payment proof', 'required' => true],
                ],
                'extra_operational_data' => [
                    ['key' => 'original_invoice', 'label' => 'Original invoice', 'type' => 'text', 'required' => true],
                    ['key' => 'reason', 'label' => 'Reason', 'type' => 'textarea', 'required' => true],
                    ['key' => 'approval', 'label' => 'Approved by', 'type' => 'text', 'required' => true],
                ],
            ],
            [
                'code' => 'NE-020', 'expense_type' => 'Asset purchase pending review',
                'accounting_class' => 'Capital expenditure', 'expense_family' => 'Property, plant and equipment',
                'simple_meaning' => 'A durable item that may need to be capitalised instead of expensed.',
                'example' => 'CNC machine, printer, laptop, truck or spray booth bought for long-term use.',
                'default_debit_gl' => 'Relevant 1400 PPE account',
                'job_id_rule' => ExpenseCode::JOB_CONDITIONAL, 'job_id_rule_note' => 'Optional only if built for a project',
                'default_cost_centre' => 'Asset-owning department', 'project_activity' => 'Capital purchase',
                'inventory_treatment' => 'Create asset record and depreciate after available for use',
                'vat_default' => 'Recoverable if eligible', 'default_vat_treatment_code' => 'STD16-REC',
                'cash_flow_class' => 'investing', 'cash_flow_note' => 'Investing',
                'requires_asset_record' => true, 'is_capex_review' => true, 'requires_supplier' => true,
                'key_control' => 'Apply WNG capitalisation policy and threshold.',
                'minimum_evidence' => [
                    ['key' => 'capex_request', 'label' => 'Approved capex request', 'required' => true],
                    ['key' => 'purchase_order', 'label' => 'Purchase order', 'required' => true],
                    ['key' => 'etims_invoice', 'label' => 'Invoice', 'required' => true],
                    ['key' => 'grn', 'label' => 'GRN and commissioning', 'required' => true],
                    ['key' => 'asset_tag', 'label' => 'Asset tag photo', 'required' => true],
                ],
                'extra_operational_data' => [
                    ['key' => 'asset_class', 'label' => 'Asset class', 'type' => 'text', 'required' => true],
                    ['key' => 'serial_number', 'label' => 'Serial number', 'type' => 'text', 'required' => true],
                    ['key' => 'location', 'label' => 'Location', 'type' => 'text', 'required' => true],
                    ['key' => 'custodian', 'label' => 'Custodian', 'type' => 'text', 'required' => true],
                    ['key' => 'useful_life', 'label' => 'Useful life (years)', 'type' => 'number', 'required' => true],
                    ['key' => 'residual_value', 'label' => 'Residual value', 'type' => 'number', 'required' => false],
                ],
            ],
            [
                'code' => 'NE-021', 'expense_type' => 'Reusable hire asset built or bought',
                'accounting_class' => 'Capital expenditure / hire asset', 'expense_family' => 'Reusable hire assets',
                'simple_meaning' => 'An item WNG owns and expects to hire out repeatedly.',
                'example' => 'Stage floor panels, exhibition counters or furniture built for repeated rentals.',
                'default_debit_gl' => 'Relevant 1500 Hire Asset account',
                'job_id_rule' => ExpenseCode::JOB_CONDITIONAL, 'job_id_rule_note' => 'Internal build order required',
                'default_cost_centre' => 'Hire Assets', 'project_activity' => 'Asset build / acquisition',
                'inventory_treatment' => 'Capitalise approved build cost and depreciate',
                'vat_default' => 'Recoverable if eligible', 'default_vat_treatment_code' => 'STD16-REC',
                'cash_flow_class' => 'investing', 'cash_flow_note' => 'Investing',
                'requires_asset_record' => true, 'is_capex_review' => true,
                'key_control' => 'Do not charge the full build to the first hire project.',
                'minimum_evidence' => [
                    ['key' => 'build_order', 'label' => 'Approved asset build order', 'required' => true],
                    ['key' => 'material_issues', 'label' => 'Material issues', 'required' => true],
                    ['key' => 'labour_sheet', 'label' => 'Labour sheet', 'required' => true],
                    ['key' => 'commissioning', 'label' => 'Commissioning record', 'required' => true],
                ],
                'extra_operational_data' => [
                    ['key' => 'asset_family', 'label' => 'Asset family', 'type' => 'text', 'required' => true],
                    ['key' => 'unit_count', 'label' => 'Unit count', 'type' => 'number', 'required' => true],
                    ['key' => 'dimensions', 'label' => 'Dimensions', 'type' => 'text', 'required' => false],
                    ['key' => 'tag', 'label' => 'Asset tag', 'type' => 'text', 'required' => true],
                    ['key' => 'location', 'label' => 'Location', 'type' => 'text', 'required' => true],
                    ['key' => 'custodian', 'label' => 'Custodian', 'type' => 'text', 'required' => true],
                    ['key' => 'useful_life', 'label' => 'Useful life (years)', 'type' => 'number', 'required' => true],
                ],
            ],
            [
                'code' => 'NE-022', 'expense_type' => 'Leasehold improvement',
                'accounting_class' => 'Capital expenditure', 'expense_family' => 'Leasehold improvements',
                'simple_meaning' => 'A major improvement to rented offices or workshop that benefits more than one period.',
                'example' => 'Permanent electrical upgrade, new mezzanine or fixed office fit-out.',
                'default_debit_gl' => '1600 Leasehold Improvements',
                'job_id_rule' => ExpenseCode::JOB_CONDITIONAL, 'job_id_rule_note' => 'Use internal capex code',
                'default_cost_centre' => 'Facilities', 'project_activity' => 'Capital works',
                'inventory_treatment' => 'Capitalise and amortise over policy period/lease term',
                'vat_default' => 'Recoverable if eligible', 'default_vat_treatment_code' => 'STD16-REC',
                'cash_flow_class' => 'investing', 'cash_flow_note' => 'Investing', 'is_capex_review' => true,
                'key_control' => 'Routine repairs must remain expense; only qualifying improvements are capitalised.',
                'minimum_evidence' => [
                    ['key' => 'capex_request', 'label' => 'Approved capex', 'required' => true],
                    ['key' => 'boq', 'label' => 'BOQ and contracts', 'required' => true],
                    ['key' => 'etims_invoice', 'label' => 'Invoices', 'required' => true],
                    ['key' => 'completion_certificate', 'label' => 'Completion certificate', 'required' => true],
                ],
                'extra_operational_data' => [
                    ['key' => 'site', 'label' => 'Site', 'type' => 'text', 'required' => true],
                    ['key' => 'component', 'label' => 'Component', 'type' => 'text', 'required' => true],
                    ['key' => 'completion_date', 'label' => 'Completion date', 'type' => 'date', 'required' => true],
                    ['key' => 'useful_life', 'label' => 'Useful life (years)', 'type' => 'number', 'required' => true],
                    ['key' => 'lease_end_date', 'label' => 'Lease end date', 'type' => 'date', 'required' => true],
                ],
            ],
            [
                'code' => 'NE-023', 'expense_type' => 'Project WIP transfer to cost of sales',
                'accounting_class' => 'Internal accounting transfer', 'expense_family' => 'WIP close-out',
                'simple_meaning' => 'Costs accumulated on an open project are moved to P&L when the related revenue is recognised.',
                'example' => 'Completed exhibition booth costs moved from WIP to cost of sales.',
                'default_debit_gl' => 'Relevant 5100–5800 Cost of Sales account',
                'job_id_rule' => ExpenseCode::JOB_REQUIRED, 'job_id_rule_note' => 'Required',
                'default_cost_centre' => 'Finance / Project', 'project_activity' => 'Financial close',
                'inventory_treatment' => 'Reduce WIP',
                'vat_default' => 'No VAT on internal transfer', 'default_vat_treatment_code' => 'OOS',
                'wht_review' => 'No',
                'cash_flow_class' => 'none', 'cash_flow_note' => 'No cash flow',
                'key_control' => 'Transfer must equal the WIP relieved and must not duplicate project cost.',
                'minimum_evidence' => [
                    ['key' => 'handover', 'label' => 'Completion / handover record', 'required' => true],
                    ['key' => 'revenue_recognition', 'label' => 'Revenue-recognition record', 'required' => true],
                    ['key' => 'close_approval', 'label' => 'Project close approval', 'required' => true],
                ],
                'extra_operational_data' => [
                    ['key' => 'cost_category', 'label' => 'Cost category', 'type' => 'text', 'required' => true],
                    ['key' => 'recognition_period', 'label' => 'Recognition period', 'type' => 'text', 'required' => true],
                ],
            ],
        ];
    }
}
